openapi: 3.0.1
info:
  title: SageToQuickbase_API
  description: API Definition of SageToQuickbase_API
  version: 1.0.0
servers:
- url: http://localhost:8290/sageToQuickbase
paths:
  /AccessBuild:
    get:
      responses:
        default:
          description: Default response
