openapi: 3.0.1
info:
  title: UpdateQBCRMsites
  description: API Definition of UpdateQBCRMsites
  version: 1.0.0
servers:
- url: http://localhost:8290/update
paths:
  /AccessBuild:
    get:
      responses:
        default:
          description: Default response
